name: lidea
description: Loading, reading, writing file logic
version: 0.0.5
author:
homepage:

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  intl: ^0.17.0
  archive: ^3.1.2
  firebase_analytics: ^8.1.0
  connectivity: ^3.0.6
  provider: '>=5.0.0-nullsafety.5 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
