name: lidea
description: Loading, reading, writing file logic
version: 0.2.3
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  intl: ^0.17.0

  archive: ^3.2.0
  crypto: ^3.0.1
  # Web?
  path_provider: ^2.0.9

  provider: ^6.0.2

  shared_preferences: ^2.0.13
  connectivity_plus: ^2.2.0
  share_plus: ^3.0.4

  hive_flutter: ^1.1.0

  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1

  cached_network_image: ^3.2.0

  # Custom
  in_app_purchase: ^2.0.1
  sqflite: ^2.0.2
  just_audio: ^0.9.20
  # sliver_tools: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
