name: lidea
description: Loading, reading, writing file logic
version: 0.1.8
homepage:

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  provider: ^6.0.0
  archive: ^3.1.5
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  crypto: ^3.0.1
  shared_preferences: ^2.0.8
  connectivity_plus: ^2.0.2
  firebase_core: ^1.7.0
  firebase_analytics: ^8.3.3
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  flutter_facebook_auth: ^3.5.2
  cached_network_image: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
