name: lidea
description: Loading, reading, writing file logic
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: '>=5.0.0-nullsafety.5 <6.0.0'
  path_provider: ^2.0.1
  http: ^0.13.1
  firebase_analytics: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
