name: lidea
description: Loading, reading, writing file logic
version: 0.3.0+44
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.5
  intl: ^0.17.0

  archive: ^3.3.1
  crypto: ^3.0.2
  # Web?
  path_provider: ^2.0.11
  # Web?
  cached_network_image: ^3.2.2

  hive_flutter: ^1.1.0
  provider: ^6.0.3

  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^2.3.7
  share_plus: ^4.1.0


  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.5
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  google_sign_in: ^5.4.1
  sign_in_with_apple: ^4.1.0
  flutter_facebook_auth: ^4.4.1+1

  # Custom
  in_app_purchase: ^3.0.7
  sqflite: ^2.0.3+1
  just_audio: ^0.9.29
  audio_service: ^0.18.7
  # audio_session: ^0.1.10
  rxdart: ^0.27.5
  flutter_tts: ^3.5.3
  # sliver_tools: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
